// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DeviceName.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceName struct {
	EphemeralPublic      []byte   `protobuf:"bytes,1,opt,name=ephemeralPublic" json:"ephemeralPublic,omitempty"`
	SyntheticIv          []byte   `protobuf:"bytes,2,opt,name=syntheticIv" json:"syntheticIv,omitempty"`
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext" json:"ciphertext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceName) Reset()         { *m = DeviceName{} }
func (m *DeviceName) String() string { return proto.CompactTextString(m) }
func (*DeviceName) ProtoMessage()    {}
func (*DeviceName) Descriptor() ([]byte, []int) {
	return fileDescriptor_54ffbbfa8785845e, []int{0}
}

func (m *DeviceName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceName.Unmarshal(m, b)
}
func (m *DeviceName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceName.Marshal(b, m, deterministic)
}
func (m *DeviceName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceName.Merge(m, src)
}
func (m *DeviceName) XXX_Size() int {
	return xxx_messageInfo_DeviceName.Size(m)
}
func (m *DeviceName) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceName.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceName proto.InternalMessageInfo

func (m *DeviceName) GetEphemeralPublic() []byte {
	if m != nil {
		return m.EphemeralPublic
	}
	return nil
}

func (m *DeviceName) GetSyntheticIv() []byte {
	if m != nil {
		return m.SyntheticIv
	}
	return nil
}

func (m *DeviceName) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func init() {
	proto.RegisterType((*DeviceName)(nil), "signalservice.DeviceName")
}

func init() { proto.RegisterFile("DeviceName.proto", fileDescriptor_54ffbbfa8785845e) }

var fileDescriptor_54ffbbfa8785845e = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x70, 0x49, 0x2d, 0xcb,
	0x4c, 0x4e, 0xf5, 0x4b, 0xcc, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xce,
	0x4c, 0xcf, 0x4b, 0xcc, 0x29, 0x4e, 0x2d, 0x02, 0x49, 0x28, 0x55, 0x70, 0x71, 0x21, 0x94, 0x08,
	0x69, 0x70, 0xf1, 0xa7, 0x16, 0x64, 0xa4, 0xe6, 0xa6, 0x16, 0x25, 0xe6, 0x04, 0x94, 0x26, 0xe5,
	0x64, 0x26, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xa1, 0x0b, 0x0b, 0x29, 0x70, 0x71, 0x17,
	0x57, 0xe6, 0x95, 0x64, 0xa4, 0x96, 0x64, 0x26, 0x7b, 0x96, 0x49, 0x30, 0x81, 0x55, 0x21, 0x0b,
	0x09, 0xc9, 0x71, 0x71, 0x25, 0x67, 0x16, 0x64, 0xa4, 0x16, 0x95, 0xa4, 0x56, 0x94, 0x48, 0x30,
	0x83, 0x15, 0x20, 0x89, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91, 0x9c, 0xaa, 0xbe, 0x9b, 0x00,
	0x00, 0x00,
}
