// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Stickers.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StickerPack struct {
	Title                *string                `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Author               *string                `protobuf:"bytes,2,opt,name=author" json:"author,omitempty"`
	Cover                *StickerPack_Sticker   `protobuf:"bytes,3,opt,name=cover" json:"cover,omitempty"`
	Stickers             []*StickerPack_Sticker `protobuf:"bytes,4,rep,name=stickers" json:"stickers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StickerPack) Reset()         { *m = StickerPack{} }
func (m *StickerPack) String() string { return proto.CompactTextString(m) }
func (*StickerPack) ProtoMessage()    {}
func (*StickerPack) Descriptor() ([]byte, []int) {
	return fileDescriptor_7085f82e23806fe1, []int{0}
}

func (m *StickerPack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StickerPack.Unmarshal(m, b)
}
func (m *StickerPack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StickerPack.Marshal(b, m, deterministic)
}
func (m *StickerPack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StickerPack.Merge(m, src)
}
func (m *StickerPack) XXX_Size() int {
	return xxx_messageInfo_StickerPack.Size(m)
}
func (m *StickerPack) XXX_DiscardUnknown() {
	xxx_messageInfo_StickerPack.DiscardUnknown(m)
}

var xxx_messageInfo_StickerPack proto.InternalMessageInfo

func (m *StickerPack) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *StickerPack) GetAuthor() string {
	if m != nil && m.Author != nil {
		return *m.Author
	}
	return ""
}

func (m *StickerPack) GetCover() *StickerPack_Sticker {
	if m != nil {
		return m.Cover
	}
	return nil
}

func (m *StickerPack) GetStickers() []*StickerPack_Sticker {
	if m != nil {
		return m.Stickers
	}
	return nil
}

type StickerPack_Sticker struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Emoji                *string  `protobuf:"bytes,2,opt,name=emoji" json:"emoji,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StickerPack_Sticker) Reset()         { *m = StickerPack_Sticker{} }
func (m *StickerPack_Sticker) String() string { return proto.CompactTextString(m) }
func (*StickerPack_Sticker) ProtoMessage()    {}
func (*StickerPack_Sticker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7085f82e23806fe1, []int{0, 0}
}

func (m *StickerPack_Sticker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StickerPack_Sticker.Unmarshal(m, b)
}
func (m *StickerPack_Sticker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StickerPack_Sticker.Marshal(b, m, deterministic)
}
func (m *StickerPack_Sticker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StickerPack_Sticker.Merge(m, src)
}
func (m *StickerPack_Sticker) XXX_Size() int {
	return xxx_messageInfo_StickerPack_Sticker.Size(m)
}
func (m *StickerPack_Sticker) XXX_DiscardUnknown() {
	xxx_messageInfo_StickerPack_Sticker.DiscardUnknown(m)
}

var xxx_messageInfo_StickerPack_Sticker proto.InternalMessageInfo

func (m *StickerPack_Sticker) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *StickerPack_Sticker) GetEmoji() string {
	if m != nil && m.Emoji != nil {
		return *m.Emoji
	}
	return ""
}

func init() {
	proto.RegisterType((*StickerPack)(nil), "signalservice.StickerPack")
	proto.RegisterType((*StickerPack_Sticker)(nil), "signalservice.StickerPack.Sticker")
}

func init() { proto.RegisterFile("Stickers.proto", fileDescriptor_7085f82e23806fe1) }

var fileDescriptor_7085f82e23806fe1 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x2e, 0xc9, 0x4c,
	0xce, 0x4e, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0xce, 0x4c, 0xcf,
	0x4b, 0xcc, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0x7a, 0xc6, 0xc8, 0xc5, 0x0d, 0x55,
	0x11, 0x90, 0x98, 0x9c, 0x2d, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x59, 0x92, 0x93, 0x2a, 0xc1, 0xa8,
	0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x89, 0x71, 0xb1, 0x25, 0x96, 0x96, 0x64, 0xe4, 0x17,
	0x49, 0x30, 0x81, 0x85, 0xa1, 0x3c, 0x21, 0x0b, 0x2e, 0xd6, 0xe4, 0xfc, 0xb2, 0xd4, 0x22, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x25, 0x3d, 0x14, 0xc3, 0xf5, 0x90, 0x0c, 0x86, 0xb1, 0x83,
	0x20, 0x1a, 0x84, 0xec, 0xb8, 0x38, 0x8a, 0xa1, 0x0e, 0x93, 0x60, 0x51, 0x60, 0x26, 0x52, 0x33,
	0x5c, 0x8f, 0x94, 0x3e, 0x17, 0x3b, 0x54, 0x50, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0xec, 0x5e,
	0xde, 0x20, 0xa6, 0xcc, 0x14, 0x90, 0x17, 0x52, 0x73, 0xf3, 0xb3, 0x32, 0xa1, 0x6e, 0x85, 0x70,
	0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x37, 0xdf, 0x82, 0x08, 0x01, 0x00, 0x00,
}
