// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SubProtocol.proto

//*
// Copyright (C) 2014 Open WhisperSystems
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WebSocketMessage_Type int32

const (
	WebSocketMessage_UNKNOWN  WebSocketMessage_Type = 0
	WebSocketMessage_REQUEST  WebSocketMessage_Type = 1
	WebSocketMessage_RESPONSE WebSocketMessage_Type = 2
)

var WebSocketMessage_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "REQUEST",
	2: "RESPONSE",
}

var WebSocketMessage_Type_value = map[string]int32{
	"UNKNOWN":  0,
	"REQUEST":  1,
	"RESPONSE": 2,
}

func (x WebSocketMessage_Type) Enum() *WebSocketMessage_Type {
	p := new(WebSocketMessage_Type)
	*p = x
	return p
}

func (x WebSocketMessage_Type) String() string {
	return proto.EnumName(WebSocketMessage_Type_name, int32(x))
}

func (x *WebSocketMessage_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(WebSocketMessage_Type_value, data, "WebSocketMessage_Type")
	if err != nil {
		return err
	}
	*x = WebSocketMessage_Type(value)
	return nil
}

func (WebSocketMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_316c09670fe84e53, []int{2, 0}
}

type WebSocketRequestMessage struct {
	Verb                 *string  `protobuf:"bytes,1,opt,name=verb" json:"verb,omitempty"`
	Path                 *string  `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Headers              []string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	Id                   *uint64  `protobuf:"varint,4,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebSocketRequestMessage) Reset()         { *m = WebSocketRequestMessage{} }
func (m *WebSocketRequestMessage) String() string { return proto.CompactTextString(m) }
func (*WebSocketRequestMessage) ProtoMessage()    {}
func (*WebSocketRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_316c09670fe84e53, []int{0}
}

func (m *WebSocketRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketRequestMessage.Unmarshal(m, b)
}
func (m *WebSocketRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketRequestMessage.Marshal(b, m, deterministic)
}
func (m *WebSocketRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketRequestMessage.Merge(m, src)
}
func (m *WebSocketRequestMessage) XXX_Size() int {
	return xxx_messageInfo_WebSocketRequestMessage.Size(m)
}
func (m *WebSocketRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketRequestMessage proto.InternalMessageInfo

func (m *WebSocketRequestMessage) GetVerb() string {
	if m != nil && m.Verb != nil {
		return *m.Verb
	}
	return ""
}

func (m *WebSocketRequestMessage) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *WebSocketRequestMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *WebSocketRequestMessage) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebSocketRequestMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type WebSocketResponseMessage struct {
	Id                   *uint64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Status               *uint32  `protobuf:"varint,2,opt,name=status" json:"status,omitempty"`
	Message              *string  `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	Headers              []string `protobuf:"bytes,5,rep,name=headers" json:"headers,omitempty"`
	Body                 []byte   `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebSocketResponseMessage) Reset()         { *m = WebSocketResponseMessage{} }
func (m *WebSocketResponseMessage) String() string { return proto.CompactTextString(m) }
func (*WebSocketResponseMessage) ProtoMessage()    {}
func (*WebSocketResponseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_316c09670fe84e53, []int{1}
}

func (m *WebSocketResponseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketResponseMessage.Unmarshal(m, b)
}
func (m *WebSocketResponseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketResponseMessage.Marshal(b, m, deterministic)
}
func (m *WebSocketResponseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketResponseMessage.Merge(m, src)
}
func (m *WebSocketResponseMessage) XXX_Size() int {
	return xxx_messageInfo_WebSocketResponseMessage.Size(m)
}
func (m *WebSocketResponseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketResponseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketResponseMessage proto.InternalMessageInfo

func (m *WebSocketResponseMessage) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *WebSocketResponseMessage) GetStatus() uint32 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *WebSocketResponseMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func (m *WebSocketResponseMessage) GetHeaders() []string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *WebSocketResponseMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type WebSocketMessage struct {
	Type                 *WebSocketMessage_Type    `protobuf:"varint,1,opt,name=type,enum=signalservice.WebSocketMessage_Type" json:"type,omitempty"`
	Request              *WebSocketRequestMessage  `protobuf:"bytes,2,opt,name=request" json:"request,omitempty"`
	Response             *WebSocketResponseMessage `protobuf:"bytes,3,opt,name=response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *WebSocketMessage) Reset()         { *m = WebSocketMessage{} }
func (m *WebSocketMessage) String() string { return proto.CompactTextString(m) }
func (*WebSocketMessage) ProtoMessage()    {}
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_316c09670fe84e53, []int{2}
}

func (m *WebSocketMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSocketMessage.Unmarshal(m, b)
}
func (m *WebSocketMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSocketMessage.Marshal(b, m, deterministic)
}
func (m *WebSocketMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSocketMessage.Merge(m, src)
}
func (m *WebSocketMessage) XXX_Size() int {
	return xxx_messageInfo_WebSocketMessage.Size(m)
}
func (m *WebSocketMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSocketMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WebSocketMessage proto.InternalMessageInfo

func (m *WebSocketMessage) GetType() WebSocketMessage_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return WebSocketMessage_UNKNOWN
}

func (m *WebSocketMessage) GetRequest() *WebSocketRequestMessage {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *WebSocketMessage) GetResponse() *WebSocketResponseMessage {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterEnum("signalservice.WebSocketMessage_Type", WebSocketMessage_Type_name, WebSocketMessage_Type_value)
	proto.RegisterType((*WebSocketRequestMessage)(nil), "signalservice.WebSocketRequestMessage")
	proto.RegisterType((*WebSocketResponseMessage)(nil), "signalservice.WebSocketResponseMessage")
	proto.RegisterType((*WebSocketMessage)(nil), "signalservice.WebSocketMessage")
}

func init() { proto.RegisterFile("SubProtocol.proto", fileDescriptor_316c09670fe84e53) }

var fileDescriptor_316c09670fe84e53 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x85, 0xa2, 0x6d, 0xb7, 0x7f, 0x82, 0x7b, 0x50, 0x8e, 0x84, 0x18, 0xe5, 0xb4, 0x31,
	0x3d, 0x79, 0x34, 0x1a, 0x4e, 0x46, 0x5a, 0x97, 0x36, 0x3d, 0x43, 0x19, 0x5b, 0x62, 0x5b, 0x70,
	0x67, 0x69, 0xc3, 0xc9, 0x83, 0x37, 0x3f, 0xb5, 0x61, 0x29, 0xd5, 0x9a, 0xd4, 0xdb, 0x7b, 0x93,
	0x79, 0xcc, 0x8f, 0x97, 0x25, 0xe7, 0x41, 0x1e, 0x8d, 0x44, 0x2a, 0xd3, 0x59, 0xba, 0x64, 0x59,
	0x29, 0x68, 0x0f, 0x93, 0xf9, 0x3a, 0x5c, 0x22, 0x88, 0x4d, 0x32, 0x03, 0xe7, 0x83, 0x5c, 0x4e,
	0x21, 0x0a, 0xd2, 0xd9, 0x1b, 0x48, 0x0e, 0xef, 0x39, 0xa0, 0x7c, 0x06, 0xc4, 0x70, 0x0e, 0x94,
	0x12, 0x63, 0x03, 0x22, 0xb2, 0x34, 0x5b, 0x73, 0xdb, 0x5c, 0xe9, 0x72, 0x96, 0x85, 0x72, 0x61,
	0xe9, 0xd5, 0xac, 0xd4, 0xe5, 0x2c, 0x4a, 0xe3, 0xc2, 0x6a, 0xd8, 0x9a, 0xdb, 0xe5, 0x4a, 0x53,
	0x8b, 0x34, 0x17, 0x10, 0xc6, 0x20, 0xd0, 0x3a, 0xb5, 0x1b, 0x6e, 0x9b, 0xd7, 0x96, 0xf6, 0x89,
	0x9e, 0xc4, 0x96, 0x61, 0x6b, 0xae, 0xc1, 0xf5, 0x24, 0x76, 0xbe, 0x34, 0x62, 0xfd, 0x22, 0xc0,
	0x2c, 0x5d, 0x23, 0xd4, 0x08, 0xd5, 0xb2, 0x56, 0x2f, 0xd3, 0x0b, 0x72, 0x86, 0x32, 0x94, 0x39,
	0x2a, 0x80, 0x1e, 0xdf, 0xb9, 0xf2, 0xdc, 0xaa, 0x8a, 0x28, 0x8a, 0x36, 0xaf, 0xed, 0x3f, 0x20,
	0x35, 0xb6, 0xf1, 0x83, 0xed, 0x7c, 0xea, 0xc4, 0xdc, 0xc3, 0xd4, 0x10, 0x77, 0xc4, 0x90, 0x45,
	0x06, 0x0a, 0xa3, 0x3f, 0xb8, 0x62, 0x07, 0x05, 0xb2, 0xbf, 0xeb, 0x6c, 0x5c, 0x64, 0xc0, 0x55,
	0x82, 0xde, 0x93, 0xa6, 0xa8, 0x3a, 0x55, 0xbc, 0x9d, 0xc1, 0xf5, 0xb1, 0xf0, 0x61, 0xf5, 0xbc,
	0x8e, 0xd1, 0x47, 0xd2, 0x12, 0xbb, 0x4e, 0xd4, 0x9f, 0x75, 0x06, 0x37, 0xc7, 0x3f, 0x71, 0xd0,
	0x1d, 0xdf, 0x07, 0x1d, 0x46, 0x8c, 0x12, 0x8a, 0x76, 0x48, 0x73, 0xe2, 0x3f, 0xf9, 0xc3, 0xa9,
	0x6f, 0x9e, 0x94, 0x86, 0x7b, 0x2f, 0x13, 0x2f, 0x18, 0x9b, 0x1a, 0xed, 0x92, 0x16, 0xf7, 0x82,
	0xd1, 0xd0, 0x0f, 0x3c, 0x53, 0x7f, 0xb8, 0x25, 0x2c, 0x15, 0x73, 0xb6, 0x5d, 0x24, 0x98, 0x81,
	0xc0, 0x02, 0x25, 0xac, 0x90, 0x6d, 0x21, 0x42, 0x75, 0x88, 0xed, 0xba, 0xc5, 0xea, 0x45, 0x45,
	0xf9, 0xeb, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0xc6, 0x51, 0x34, 0x68, 0x02, 0x00, 0x00,
}
