// Code generated by protoc-gen-go. DO NOT EDIT.
// source: UnidentifiedDelivery.proto

package signalservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnidentifiedSenderMessage_Message_Type int32

const (
	UnidentifiedSenderMessage_Message_PREKEY_MESSAGE UnidentifiedSenderMessage_Message_Type = 1
	UnidentifiedSenderMessage_Message_MESSAGE        UnidentifiedSenderMessage_Message_Type = 2
)

var UnidentifiedSenderMessage_Message_Type_name = map[int32]string{
	1: "PREKEY_MESSAGE",
	2: "MESSAGE",
}

var UnidentifiedSenderMessage_Message_Type_value = map[string]int32{
	"PREKEY_MESSAGE": 1,
	"MESSAGE":        2,
}

func (x UnidentifiedSenderMessage_Message_Type) Enum() *UnidentifiedSenderMessage_Message_Type {
	p := new(UnidentifiedSenderMessage_Message_Type)
	*p = x
	return p
}

func (x UnidentifiedSenderMessage_Message_Type) String() string {
	return proto.EnumName(UnidentifiedSenderMessage_Message_Type_name, int32(x))
}

func (x *UnidentifiedSenderMessage_Message_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UnidentifiedSenderMessage_Message_Type_value, data, "UnidentifiedSenderMessage_Message_Type")
	if err != nil {
		return err
	}
	*x = UnidentifiedSenderMessage_Message_Type(value)
	return nil
}

func (UnidentifiedSenderMessage_Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{2, 0, 0}
}

type ServerCertificate struct {
	Certificate          []byte   `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerCertificate) Reset()         { *m = ServerCertificate{} }
func (m *ServerCertificate) String() string { return proto.CompactTextString(m) }
func (*ServerCertificate) ProtoMessage()    {}
func (*ServerCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{0}
}

func (m *ServerCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCertificate.Unmarshal(m, b)
}
func (m *ServerCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCertificate.Marshal(b, m, deterministic)
}
func (m *ServerCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCertificate.Merge(m, src)
}
func (m *ServerCertificate) XXX_Size() int {
	return xxx_messageInfo_ServerCertificate.Size(m)
}
func (m *ServerCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCertificate proto.InternalMessageInfo

func (m *ServerCertificate) GetCertificate() []byte {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *ServerCertificate) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type ServerCertificate_Certificate struct {
	Id                   *uint32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerCertificate_Certificate) Reset()         { *m = ServerCertificate_Certificate{} }
func (m *ServerCertificate_Certificate) String() string { return proto.CompactTextString(m) }
func (*ServerCertificate_Certificate) ProtoMessage()    {}
func (*ServerCertificate_Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{0, 0}
}

func (m *ServerCertificate_Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerCertificate_Certificate.Unmarshal(m, b)
}
func (m *ServerCertificate_Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerCertificate_Certificate.Marshal(b, m, deterministic)
}
func (m *ServerCertificate_Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerCertificate_Certificate.Merge(m, src)
}
func (m *ServerCertificate_Certificate) XXX_Size() int {
	return xxx_messageInfo_ServerCertificate_Certificate.Size(m)
}
func (m *ServerCertificate_Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerCertificate_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_ServerCertificate_Certificate proto.InternalMessageInfo

func (m *ServerCertificate_Certificate) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ServerCertificate_Certificate) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type SenderCertificate struct {
	Certificate          []byte   `protobuf:"bytes,1,opt,name=certificate" json:"certificate,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=signature" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SenderCertificate) Reset()         { *m = SenderCertificate{} }
func (m *SenderCertificate) String() string { return proto.CompactTextString(m) }
func (*SenderCertificate) ProtoMessage()    {}
func (*SenderCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{1}
}

func (m *SenderCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderCertificate.Unmarshal(m, b)
}
func (m *SenderCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderCertificate.Marshal(b, m, deterministic)
}
func (m *SenderCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderCertificate.Merge(m, src)
}
func (m *SenderCertificate) XXX_Size() int {
	return xxx_messageInfo_SenderCertificate.Size(m)
}
func (m *SenderCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_SenderCertificate proto.InternalMessageInfo

func (m *SenderCertificate) GetCertificate() []byte {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (m *SenderCertificate) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SenderCertificate_Certificate struct {
	Sender               *string            `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	SenderDevice         *uint32            `protobuf:"varint,2,opt,name=senderDevice" json:"senderDevice,omitempty"`
	Expires              *uint64            `protobuf:"fixed64,3,opt,name=expires" json:"expires,omitempty"`
	IdentityKey          []byte             `protobuf:"bytes,4,opt,name=identityKey" json:"identityKey,omitempty"`
	Signer               *ServerCertificate `protobuf:"bytes,5,opt,name=signer" json:"signer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SenderCertificate_Certificate) Reset()         { *m = SenderCertificate_Certificate{} }
func (m *SenderCertificate_Certificate) String() string { return proto.CompactTextString(m) }
func (*SenderCertificate_Certificate) ProtoMessage()    {}
func (*SenderCertificate_Certificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{1, 0}
}

func (m *SenderCertificate_Certificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SenderCertificate_Certificate.Unmarshal(m, b)
}
func (m *SenderCertificate_Certificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SenderCertificate_Certificate.Marshal(b, m, deterministic)
}
func (m *SenderCertificate_Certificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SenderCertificate_Certificate.Merge(m, src)
}
func (m *SenderCertificate_Certificate) XXX_Size() int {
	return xxx_messageInfo_SenderCertificate_Certificate.Size(m)
}
func (m *SenderCertificate_Certificate) XXX_DiscardUnknown() {
	xxx_messageInfo_SenderCertificate_Certificate.DiscardUnknown(m)
}

var xxx_messageInfo_SenderCertificate_Certificate proto.InternalMessageInfo

func (m *SenderCertificate_Certificate) GetSender() string {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return ""
}

func (m *SenderCertificate_Certificate) GetSenderDevice() uint32 {
	if m != nil && m.SenderDevice != nil {
		return *m.SenderDevice
	}
	return 0
}

func (m *SenderCertificate_Certificate) GetExpires() uint64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

func (m *SenderCertificate_Certificate) GetIdentityKey() []byte {
	if m != nil {
		return m.IdentityKey
	}
	return nil
}

func (m *SenderCertificate_Certificate) GetSigner() *ServerCertificate {
	if m != nil {
		return m.Signer
	}
	return nil
}

type UnidentifiedSenderMessage struct {
	EphemeralPublic      []byte   `protobuf:"bytes,1,opt,name=ephemeralPublic" json:"ephemeralPublic,omitempty"`
	EncryptedStatic      []byte   `protobuf:"bytes,2,opt,name=encryptedStatic" json:"encryptedStatic,omitempty"`
	EncryptedMessage     []byte   `protobuf:"bytes,3,opt,name=encryptedMessage" json:"encryptedMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnidentifiedSenderMessage) Reset()         { *m = UnidentifiedSenderMessage{} }
func (m *UnidentifiedSenderMessage) String() string { return proto.CompactTextString(m) }
func (*UnidentifiedSenderMessage) ProtoMessage()    {}
func (*UnidentifiedSenderMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{2}
}

func (m *UnidentifiedSenderMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnidentifiedSenderMessage.Unmarshal(m, b)
}
func (m *UnidentifiedSenderMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnidentifiedSenderMessage.Marshal(b, m, deterministic)
}
func (m *UnidentifiedSenderMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnidentifiedSenderMessage.Merge(m, src)
}
func (m *UnidentifiedSenderMessage) XXX_Size() int {
	return xxx_messageInfo_UnidentifiedSenderMessage.Size(m)
}
func (m *UnidentifiedSenderMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UnidentifiedSenderMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UnidentifiedSenderMessage proto.InternalMessageInfo

func (m *UnidentifiedSenderMessage) GetEphemeralPublic() []byte {
	if m != nil {
		return m.EphemeralPublic
	}
	return nil
}

func (m *UnidentifiedSenderMessage) GetEncryptedStatic() []byte {
	if m != nil {
		return m.EncryptedStatic
	}
	return nil
}

func (m *UnidentifiedSenderMessage) GetEncryptedMessage() []byte {
	if m != nil {
		return m.EncryptedMessage
	}
	return nil
}

type UnidentifiedSenderMessage_Message struct {
	Type                 *UnidentifiedSenderMessage_Message_Type `protobuf:"varint,1,opt,name=type,enum=signalservice.UnidentifiedSenderMessage_Message_Type" json:"type,omitempty"`
	SenderCertificate    *SenderCertificate                      `protobuf:"bytes,2,opt,name=senderCertificate" json:"senderCertificate,omitempty"`
	Content              []byte                                  `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *UnidentifiedSenderMessage_Message) Reset()         { *m = UnidentifiedSenderMessage_Message{} }
func (m *UnidentifiedSenderMessage_Message) String() string { return proto.CompactTextString(m) }
func (*UnidentifiedSenderMessage_Message) ProtoMessage()    {}
func (*UnidentifiedSenderMessage_Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_57902ff3937a2d55, []int{2, 0}
}

func (m *UnidentifiedSenderMessage_Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnidentifiedSenderMessage_Message.Unmarshal(m, b)
}
func (m *UnidentifiedSenderMessage_Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnidentifiedSenderMessage_Message.Marshal(b, m, deterministic)
}
func (m *UnidentifiedSenderMessage_Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnidentifiedSenderMessage_Message.Merge(m, src)
}
func (m *UnidentifiedSenderMessage_Message) XXX_Size() int {
	return xxx_messageInfo_UnidentifiedSenderMessage_Message.Size(m)
}
func (m *UnidentifiedSenderMessage_Message) XXX_DiscardUnknown() {
	xxx_messageInfo_UnidentifiedSenderMessage_Message.DiscardUnknown(m)
}

var xxx_messageInfo_UnidentifiedSenderMessage_Message proto.InternalMessageInfo

func (m *UnidentifiedSenderMessage_Message) GetType() UnidentifiedSenderMessage_Message_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return UnidentifiedSenderMessage_Message_PREKEY_MESSAGE
}

func (m *UnidentifiedSenderMessage_Message) GetSenderCertificate() *SenderCertificate {
	if m != nil {
		return m.SenderCertificate
	}
	return nil
}

func (m *UnidentifiedSenderMessage_Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterEnum("signalservice.UnidentifiedSenderMessage_Message_Type", UnidentifiedSenderMessage_Message_Type_name, UnidentifiedSenderMessage_Message_Type_value)
	proto.RegisterType((*ServerCertificate)(nil), "signalservice.ServerCertificate")
	proto.RegisterType((*ServerCertificate_Certificate)(nil), "signalservice.ServerCertificate.Certificate")
	proto.RegisterType((*SenderCertificate)(nil), "signalservice.SenderCertificate")
	proto.RegisterType((*SenderCertificate_Certificate)(nil), "signalservice.SenderCertificate.Certificate")
	proto.RegisterType((*UnidentifiedSenderMessage)(nil), "signalservice.UnidentifiedSenderMessage")
	proto.RegisterType((*UnidentifiedSenderMessage_Message)(nil), "signalservice.UnidentifiedSenderMessage.Message")
}

func init() { proto.RegisterFile("UnidentifiedDelivery.proto", fileDescriptor_57902ff3937a2d55) }

var fileDescriptor_57902ff3937a2d55 = []byte{
	// 440 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x95, 0xd3, 0xd2, 0x6a, 0xa7, 0x1f, 0x74, 0x7d, 0x40, 0xa1, 0xe2, 0x10, 0x45, 0x42, 0x54,
	0x1c, 0x82, 0xb4, 0x12, 0x88, 0x2b, 0xcb, 0x56, 0x08, 0xad, 0x16, 0x55, 0x0e, 0x08, 0x71, 0x42,
	0x59, 0x67, 0xe8, 0x5a, 0x64, 0x93, 0xc8, 0xf6, 0x16, 0x7c, 0x87, 0x9f, 0xc0, 0xef, 0xe1, 0xe7,
	0xf0, 0x37, 0x90, 0xed, 0x84, 0x4d, 0x53, 0xb8, 0x71, 0x8a, 0xe7, 0x65, 0xfc, 0xe6, 0xcd, 0x7b,
	0x09, 0x2c, 0xdf, 0x95, 0x22, 0xc7, 0x52, 0x8b, 0x4f, 0x02, 0xf3, 0x33, 0x2c, 0xc4, 0x0e, 0xa5,
	0x49, 0x6a, 0x59, 0xe9, 0x8a, 0xce, 0x94, 0xd8, 0x96, 0x59, 0xa1, 0x50, 0xee, 0x04, 0xc7, 0xf8,
	0x1b, 0x81, 0xe3, 0x14, 0xe5, 0x0e, 0xe5, 0x4b, 0x94, 0xf6, 0x02, 0xcf, 0x34, 0xd2, 0x08, 0x26,
	0xfc, 0xb6, 0x0c, 0x49, 0x44, 0x56, 0x53, 0xd6, 0x85, 0xe8, 0x03, 0x38, 0x72, 0x44, 0xfa, 0x46,
	0x62, 0x18, 0xb8, 0xf7, 0xb7, 0xc0, 0xf2, 0x09, 0x4c, 0xba, 0x74, 0x73, 0x08, 0x44, 0xee, 0x58,
	0x66, 0x2c, 0x10, 0x39, 0x5d, 0xc0, 0xe0, 0x33, 0x9a, 0xe6, 0x9a, 0x3d, 0xc6, 0x3f, 0x02, 0x2b,
	0xa3, 0xcc, 0xff, 0xaf, 0x8c, 0x9f, 0x64, 0x5f, 0xc7, 0x3d, 0x18, 0x29, 0x37, 0xc4, 0x51, 0x1d,
	0xb1, 0xa6, 0xa2, 0x31, 0x4c, 0xfd, 0xe9, 0x0c, 0xad, 0x29, 0x8e, 0x68, 0xc6, 0xf6, 0x30, 0x1a,
	0xc2, 0x18, 0xbf, 0xd6, 0x42, 0xa2, 0x0a, 0x07, 0x11, 0x59, 0x8d, 0x58, 0x5b, 0x5a, 0x95, 0xde,
	0x6d, 0x6d, 0xce, 0xd1, 0x84, 0x43, 0xaf, 0xb2, 0x03, 0xd1, 0xe7, 0x30, 0xb2, 0xa2, 0x50, 0x86,
	0x77, 0x22, 0xb2, 0x9a, 0x9c, 0x44, 0xc9, 0x5e, 0x08, 0xc9, 0x41, 0x00, 0xac, 0xe9, 0x8f, 0xbf,
	0x0f, 0xe0, 0x7e, 0x37, 0x4c, 0xef, 0xd1, 0x05, 0x2a, 0x95, 0x6d, 0x91, 0xae, 0xe0, 0x2e, 0xd6,
	0x57, 0x78, 0x8d, 0x32, 0x2b, 0x36, 0x37, 0x97, 0x85, 0xe0, 0x8d, 0x47, 0x7d, 0xd8, 0x75, 0x96,
	0x5c, 0x9a, 0x5a, 0x63, 0x9e, 0xea, 0x4c, 0x0b, 0xde, 0xb8, 0xd5, 0x87, 0xe9, 0x63, 0x58, 0xfc,
	0x81, 0x9a, 0x39, 0x6e, 0xe1, 0x29, 0x3b, 0xc0, 0x97, 0xbf, 0x08, 0x8c, 0x5b, 0x2d, 0xaf, 0x61,
	0xa8, 0x4d, 0xed, 0x43, 0x9a, 0x9f, 0x3c, 0xed, 0x6d, 0xf8, 0xcf, 0x1d, 0x92, 0xf6, 0xf9, 0xd6,
	0xd4, 0xc8, 0x1c, 0x05, 0x7d, 0x03, 0xc7, 0xaa, 0xff, 0x2d, 0x38, 0xb9, 0x7f, 0x73, 0xae, 0xd7,
	0xc7, 0x0e, 0xaf, 0xda, 0xe8, 0x78, 0x55, 0x6a, 0x2c, 0x75, 0xb3, 0x49, 0x5b, 0xc6, 0x8f, 0x60,
	0x68, 0xe7, 0x52, 0x0a, 0xf3, 0x0d, 0x5b, 0x9f, 0xaf, 0x3f, 0x7c, 0xbc, 0x58, 0xa7, 0xe9, 0x8b,
	0x57, 0xeb, 0x05, 0xa1, 0x13, 0x18, 0xb7, 0x45, 0x70, 0xfa, 0x0c, 0x1e, 0x56, 0x72, 0x9b, 0x7c,
	0xb9, 0x12, 0xaa, 0x46, 0xa9, 0x8c, 0xd2, 0x78, 0xad, 0x92, 0x42, 0x5c, 0x7a, 0x39, 0xfe, 0xdf,
	0xe2, 0x55, 0x71, 0x3a, 0x7b, 0xef, 0x5b, 0x36, 0x16, 0x50, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x96, 0xf9, 0x38, 0xce, 0x8a, 0x03, 0x00, 0x00,
}
